# -*- coding: utf-8 -*-
"""collect_normal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0EGisGuIjq6alRJ1bHuimE9n1Tpty5Z
"""

import time
import csv
from pynput import keyboard

# --- 設定 ---
OUTPUT_FILENAME = "N13_normal.csv" # ★保存ファイル名

# --- 変数初期化 ---
log_data = []
pressed_keys = set()
recording = False
start_time = 0

print(f"--- 【Normal条件】収集ツール ---")
print(f"保存先: {OUTPUT_FILENAME}")
print("------------------------------------------------")
print("【Space】キーを押すと、記録がスタートします。")
print("【Esc】  キーを押すと、終了して保存します。")
print("------------------------------------------------")

def get_key_name(key):
    try:
        return key.char
    except AttributeError:
        return str(key).replace('Key.', '')

def on_press(key):
    global recording, start_time

    # --- 開始トリガー (Space) ---
    if not recording:
        if key == keyboard.Key.space:
            print("\n>>> Normal実験スタート！記録中... <<<")
            recording = True
            start_time = time.time()
            return
        else:
            # 開始前は他のキーを無視
            return

    # --- 記録中 ---
    if key in pressed_keys: return
    pressed_keys.add(key)

    # 経過時間 (ミリ秒) で記録
    current_time = (time.time() - start_time) * 1000

    log_data.append([get_key_name(key), 'press', current_time])

def on_release(key):
    global recording

    if not recording: return

    if key in pressed_keys:
        pressed_keys.remove(key)

    # 終了トリガー (Esc)
    if key == keyboard.Key.esc:
        print("\n>>> 実験終了・保存中... <<<")
        return False # リスナー停止

    current_time = (time.time() - start_time) * 1000
    log_data.append([get_key_name(key), 'release', current_time])

# --- 実行 ---
with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()

# --- 保存 ---
with open(OUTPUT_FILENAME, 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['key', 'event_type', 'timestamp_ms'])
    writer.writerows(log_data)

print(f"保存完了！ (所要時間: {log_data[-1][2]/1000:.2f}秒)")